# Generated by Django 4.1.1 on 2022-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='modelfile',
            field=models.FileField(upload_to='model/'),
        ),
    ]
